### ISSUE TITLE
要怎么使用 是替换原来py exe文件吗

### ISSUE THREAD

**Issue by wDecap** [YCCDSZXH/welearn#1]

**Comment by YCCDSZXH** [comment]
重新下载代码,运行 exe 文件就行了,
如果 exe 没法运行百度一下怎么运行 python 代码

**Comment by YCCDSZXH** [comment]
这个仓库有点问题
看下面的
https://gitee.com/xxxhhy/welearn-curriculum-finsh.git

**Comment by wDecap** [comment]
大佬这不是之前那个welearn的刷题的更新吗 你的exe我能运行 就是登入完就闪退了 刷不了题

**Comment by YCCDSZXH** [comment]
半小时前我重新提交了代码和 exe 文件,重新下载应该是没有问题了

**Comment by wDecap** [comment]
爱了爱了大佬 我让我同学给你点星星
