### ISSUE TITLE
老大出个刷时长的

### ISSUE THREAD

**Issue by 2682856025** [YCCDSZXH/welearn#2]
在gitee上刷时长的登陆不好使了

**Comment by YCCDSZXH** [comment]
https://github.com/YCCDSZXH/WelearnTimeFinsh.git
之前修复过登录模块,gitee忘记设为公开了

**Comment by 2682856025** [comment]
> https://github.com/YCCDSZXH/WelearnTimeFinsh.git
> 之前修复过登录模块，gitee忘记设为公开了

老大 我那个仓库拉你了
